version: '3.8'

services:
  database:
    image: postgres:16.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "4000:5432"
  redis:
    image: redis:6.2.6-alpine3.14
    restart: always
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"